[app]
log_level = "info"

[argocd]
namespace = "argocd"

[monitoring]
api_probe_interval = "60s"
alert_repeat_interval = "5m"
nodes_enabled = true
argocd_enabled = true

[cluster]
api_url = "https://k8s.acme.com:6443"
token = "xxx"

[telegram]
token = "xxx"
chat_id = -11111
proxy = ""
