// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/uudecode/k8s-bot/internal/config"
	"github.com/uudecode/k8s-bot/internal/di"
	"github.com/uudecode/k8s-bot/internal/logger"
	"github.com/uudecode/k8s-bot/internal/monitor"
)

// Injectors from wire.go:

func InitializeApp() (*monitor.Service, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	zerologLogger := logger.NewLogger(configConfig)
	clientset, err := di.ProvideK8sClient(configConfig)
	if err != nil {
		return nil, err
	}
	dynamicInterface, err := di.ProvideDynamicClient(configConfig)
	if err != nil {
		return nil, err
	}
	botAPI, err := di.ProvideBot(configConfig)
	if err != nil {
		return nil, err
	}
	notifier := di.ProvideNotifier(botAPI, configConfig)
	service := monitor.NewMonitorService(configConfig, zerologLogger, clientset, dynamicInterface, notifier)
	return service, nil
}
